### ISSUE TITLE
NZ DEMs

### ISSUE THREAD

**Issue by fallaciousreasoning** [DahnJ/Awesome-DEM#14]
LINZ has a 1m DEM for different regions of NZ and some people have created lower resolution DEMs from the data:

LINZ DEMs: https://data.linz.govt.nz/data/category/elevation/

8m DEM (from LINZ DEMs): https://www.opentopodata.org/datasets/nzdem/

10m DEM (interpolated from LINZ 20m contours): https://github.com/JohnLeber/NZDEM-HGT-30

**Comment by DahnJ** [comment]
Hi @fallaciousreasoning, thank you for the suggestion, added in https://github.com/DahnJ/Awesome-DEM/commit/accc199e45857dc04c8e477eaa98e9f659d9cc7c
