### ISSUE TITLE
Add French dtaset in "local" part

### ISSUE THREAD

**Issue by ThomasG77** [DahnJ/Awesome-DEM#4]
For DEM, https://geoservices.ign.fr/rgealti (1m precision for position but vary for altitude. Less than 1 meter precision except for mountains area where around 7m https://geoservices.ign.fr/sites/default/files/2021-07/DC_RGEALTI_2-0.pdf#page=11)

Add the LIDAR, ongoing acquisition campaign https://geoservices.ign.fr/lidarhd

**Comment by DahnJ** [comment]
Hi @ThomasG77, thank you for the suggestions! I have added both
